## Verzinkt - Hinweise

#### Pixelbilder

Pixelbilder erzeugen wir mit dem package PIL (Python Image Library). Graustufen werden mit den Werten 0 (schwarz) bis 255 (weiß) codiert.
In Replit muss das package PIL erst installliert werden. Dazu auf das package-Symbol clicken und nach Pillow suchen. Dann auf das Zeichen + clicken, um das package zu installieren. Mit den Anweisungen unten kann geprüft werden, ob die Installation erfolgreich war und ein Image erzeugt werden kann. Das Bild kann durch anclicken der png-Datei in Replit angeschaut werden.

In [1]:
# hier entsteht ein 100x100 Pixelbild, alle Pixel werden mit der Graustufe 200 vorbelegt
from PIL import Image
img = Image.new('L', (100,100), 200)   # mode L = Graustufen 0 - 255
img.save('bild.png')

PIL bietet uns die Möglichkeit, direkt auf die Pixel zuzugreifen und deren Wert zu verändern.

In [2]:
from PIL import Image
breite = 500
hoehe = 400
img = Image.new('L', (breite,hoehe), 0)   # mode L = Graustufen 0 - 255
pixels = img.load()   
'''
Über das 2-dimensionale pixels-Array können wir die Werte der Pixel setzen.
Der Ursprung (0,0) ist oben links
Die erste Komponente beschreibt die x-Richtung nach rechts, 
    die zweite Komponente die y-Richtung nach unten.
'''
# hier entsteht ein heller (Grauwert 240) horizontaler Streifen
for x in range(breite):
    for y in range(100,150):
        pixels[x,y] = 240
img.save('bild.png')

#### Mögliches Vorgehen

Für ein 400 x 400 Pixel Bild spendieren wir uns ein 2-dimensionales Array.  Wir können das 2-dimensionale Array als Liste von Listen implementieren, oder wir wählen ein numpy-array. Numpy-Arrays haben mehr Funktionalität und sind schneller, außerdem können wir sie bei der Sudoku-Aufgabe gut gebrauchen. 

In [6]:
# Ein 2-dimensionales Array, das mit 0 vorbesetzt ist.
import numpy as np
breite, hoehe = 400, 400
grid = np.zeros((breite, hoehe),dtype='int')
print(grid)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


Die unterschiedlichen Kristallisationskeime benennen wir mit natürlichen Zahlen 1, 2, ... Unten setzen wir einen Kristallisationskeim vom Typ 1 an die Position (0,2).  Die 1. Komponente ist die Zeile, die 2.Komponente ist die Spalte. (Achtung, das ist anders als beim pixel-Array).
Irgendwie müssen wir uns noch merken, welches Wachstumverhalten die Kristallisationskeime haben.

In [7]:
grid[0,2] = 1                   # Mit Pythonlisten müssten wir grid[0][2] = 1 schreiben.
# Keime vom Typ 1 wachsen bei einem Durchgang 1 in Richtung nach oben, 3 nach unten usw. ...
wachstum = {1: (1,3,2,3)}       # festgelegte Reihenfolge: oben unten links rechts

Das Wachstum erfolgt dann in verschiedenen Runden, bis es keine 0 mehr in unserem grid gibt. In jeder Runde gehen wir Zelle für Zelle durch unser grid, Wenn wir auf ein Kristallzelle stoßen, werden die Nachbarzellen (sofern frei) je nach Wachstumsverhalten gefüllt.

Zum Schluss ordnen wir den grid-zellen je nach Typ verschiedene Grauwerten zu und füllen damit das Pixelarray.

#### Nützliches mit numpy

In [10]:
a = np.array([0,1,1,0,2,0,1,1,2]).reshape(3,3)
a

array([[0, 1, 1],
       [0, 2, 0],
       [1, 1, 2]])

In [12]:
a == 0                 # Elementweise vergleich

array([[ True, False, False],
       [ True, False,  True],
       [False, False, False]])

In [14]:
# Feststellen, wieviele Nullen im Array vorhanden sind
anz = np.count_nonzero(a==0)  
print(anz)

3
