### Grids mit Numpy

Grids sind zweidimensionale Listen. Häufig nennt man das auch: Matrix.

In [2]:
import numpy as np

### Grids erzeugen

In [3]:
a = np.zeros((3,5),dtype='<U1')      # 3 x 5 matrix mit leeren Strings
a = np.zeros((3,5))                  # 3 x 5 matrix mit float-Nullen
a = np.zeros((3,5),dtype='int')      # 3 x 5 matrix mit int-Nullen
a = np.zeros((3,5),dtype=object)     # 3 x 5 matrix mit None

In [4]:
a = np.ones((3,5))                   # 3 x 5 matrix mit float-Einsen
a = np.ones((3,5),dtype='int')       # 3 x 5 matrix mit int-Einsen

In [5]:
a = np.full((3,5),2)                  # 3 x 5 matrix, alle Felder mit 2 initialisiert
a = np.full((3,5),'.')                # 3 x 5 matrix, alle Felder mit '.' initialisiert

In [6]:
a = np.eye(3)                         # 3 x 3 Einheitsmatrix (float)
a = np.eye(3,dtype='int')             # 3 x 3 Einheitsmatrix (int)
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [7]:
a = np.array(range(15)).reshape((3,5))        # Matrix aus range oder liste
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
# 3 x 5 Matrix mit zufällig 0 oder 1
a = np.array([np.random.randint(0,2) for _ in range(15)]).reshape((3,5))
a

array([[0, 1, 0, 0, 1],
       [1, 1, 0, 1, 1],
       [1, 1, 0, 0, 0]])

In [9]:
a.flatten()                                   # umwandeln in ein 1D-array, zurück mit reshape((3,5))

array([0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0])

#### Elemente durchlaufen

In [10]:
a = np.array([
   [6, 9, 6, 1],
   [1, 2, 8, 7],
   [3, 5, 6, 3]])

In [11]:
# Zeilen durchlaufen
rows, cols = a.shape
for i in range(rows):
    for j in range(cols):
        print(a[i,j], end= ' ')

6 9 6 1 1 2 8 7 3 5 6 3 

In [12]:
# Spalten durchlaufen
rows, cols = a.shape
for j in range(cols):
    for i in range(rows):
        print(a[i,j], end= ' ')

6 1 3 9 2 5 6 8 6 1 7 3 

#### Zeile und Spalte
```
axis = 0 # operation bezieht sich auf Spalten
axis = 1 # operation bezieht sich auf Zeile
```

In [13]:
a = np.array([
   [ 0,  1,  2,  3,  4],
   [ 5,  6,  7,  8,  9],
   [10, 11, 12, 13, 14]])

a[1,2]           # Element an Zeile 1 und Spalte 2    
a[1,:]           # Zeile 1
a[:,2]           # Spalte 2

array([ 2,  7, 12])

In [262]:
np.sum(a, axis=0) # Die Summen für jede Spalte

array([15, 18, 21, 24, 27])

In [263]:
np.sum(a, axis=1) # Die Summen für jede Zeile

array([10, 35, 60])

In [17]:
np.max(a, axis=0)   # Das Maximum für jede Spalte    # analog min
np.max(a, axis=1)   # Das Maximum für jede Zeile
np.mean(a, axis=0)  # Der Durchschnitt für jede Spalte
np.mean(a, axis=1)  # Der Durchschnitt für jede Zeile


array([ 2.,  7., 12.])

In [20]:
np.sum(a[0])        # Summe für Zeile 0    
np.sum(a[:,0])      # Summe für Spalte 0

15

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

#### Vertauschen von Zeilen und Spalten

In [224]:
# Vertauschen zweier Zeilen
a = np.array([
   [ 0,  1,  2,  3,  4],
   [ 5,  6,  7,  8,  9],
   [10, 11, 12, 13, 14],
])
a1 = a.copy()                
a1[[0,2],:] = a1[[2,0],:]      # vertausche Zeile 0 und 2
a1

array([[10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [225]:
# Vertauschen zweier Spalten    
a1 = a.copy()  
a1[:,[0,2]] = a1[:,[2,0]]      # vertausche Spalte 0 und 2
a1

array([[ 2,  1,  0,  3,  4],
       [ 7,  6,  5,  8,  9],
       [12, 11, 10, 13, 14]])

In [232]:
# Umgruppierung von Spalten
a1 = a.copy()                
a1[:,[1,2,3]]= a1[:,[2,3,1]]
a1

array([[ 0,  2,  3,  1,  4],
       [ 5,  7,  8,  6,  9],
       [10, 12, 13, 11, 14]])

#### Sortieren

In [148]:
np.random.seed(1)
a0 = [np.random.randint(1,30) for _  in range(20)]
a = np.array(a0).reshape((4,5))
a

array([[ 6, 12, 13,  9, 10],
       [12,  6, 16,  1, 17],
       [ 2, 13,  8, 14, 29],
       [ 7, 26, 19, 21,  6]])

In [140]:
b = np.sort(a,axis = 0)        # Spalten sortieren
b

array([[ 2,  6,  8,  1,  6],
       [ 6, 12, 13,  9, 10],
       [ 7, 13, 16, 14, 17],
       [12, 26, 19, 21, 29]])

In [141]:
b = np.sort(a,axis = 1)        # Zeilen sortieren
b

array([[ 6,  9, 10, 12, 13],
       [ 1,  6, 12, 16, 17],
       [ 2,  8, 13, 14, 29],
       [ 6,  7, 19, 21, 26]])

In [142]:
b = np.sort(a,axis = 0)[::-1]  # Spalten umgekehrt sortieren
b

array([[12, 26, 19, 21, 29],
       [ 7, 13, 16, 14, 17],
       [ 6, 12, 13,  9, 10],
       [ 2,  6,  8,  1,  6]])

In [153]:
b = a.transpose()              # Zeilen umgekehrt sortieren
b = np.sort(b,axis = 0)[::-1]
b = b.transpose()
b

array([[13, 12, 10,  9,  6],
       [17, 16, 12,  6,  1],
       [29, 14, 13,  8,  2],
       [26, 21, 19,  7,  6]])

#### Slicing

In [27]:
grid = np.arange(0,15,1).reshape((3,5))
grid

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [34]:
# Zeile mit Index 2 als 1D-Liste
grid[2,:]

array([10, 11, 12, 13, 14])

In [33]:
# Spalte mit Index 2 als 1D-Liste
grid[:,2]

array([ 2,  7, 12])

In [36]:
grid[0:2,:]   # Zeile 0 und 1 als 2D

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [38]:
grid[:,0:2]    # Spalten 0 und 1 als 2D

array([[ 0,  1],
       [ 5,  6],
       [10, 11]])

In [41]:
grid[0:2,1:4]   # Zeile 0,1 mit Spalten 1,2,3 als Teilbereich

array([[1, 2, 3],
       [6, 7, 8]])

#### Transposition und Drehen

In [239]:
# Transposition - Zeile 0 wird zu Spalte 0 usw.
a = np.array([
   [ 0,  1,  2,  3,  4],
   [ 5,  6,  7,  8,  9],
   [10, 11, 12, 13, 14]])
a.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [248]:
# im Uhrzeigersinn um 90 Grad drehen
a[::-1,:].T 

array([[10,  5,  0],
       [11,  6,  1],
       [12,  7,  2],
       [13,  8,  3],
       [14,  9,  4]])

In [250]:
# gegen Uhrzeigersinn um 90 Grad drehen
a[:,::-1].T

array([[ 4,  9, 14],
       [ 3,  8, 13],
       [ 2,  7, 12],
       [ 1,  6, 11],
       [ 0,  5, 10]])

In [244]:
# um 180 Grad drehen
a[::-1,::-1] 

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

#### Find

In [125]:
# Indizes für einen bestimmten Wert finden
a = np.array([np.random.randint(0,2) for _ in range(15)]).reshape((3,5))
print(a)
list(zip(*np.where(a == 1)))

[[1 0 1 1 0]
 [1 0 0 0 0]
 [1 0 0 0 0]]


[(0, 0), (0, 2), (0, 3), (1, 0), (2, 0)]

In [205]:
# Check an welchen Stellen die 2 steht
a = np.array([
   [0, 1, 1],
   [0, 2, 2],
   [1, 1, 2],
])
a == 2

array([[False, False, False],
       [False,  True,  True],
       [False, False,  True]])

In [210]:
# Anzahlen zählen
np.count_nonzero(a == 2)           # Anzahl Zweien in a

3

In [194]:
# check, an welchen Stellen die in der Liste angegebenen Werte sind
a = np.array(
    [[7, 3, 8, 3],
     [8, 6, 9, 1],
     [6, 4, 2, 3],
    ])
np.isin(a,[3,8,9])

array([[False,  True,  True,  True],
       [ True, False,  True, False],
       [False, False, False,  True]])

In [ ]:
# Die Koordinate mit dem Maximum finden
maxIdx = np.unravel_index(np.argmax(a), a.shape)

#### 2D - 1D Conversion

In [13]:
# Das Element mit Index 6 hat in einer 3x4 Matrix die Koordinate (1,2)
np.unravel_index(6,(3,4))

(1, 2)

#### Boolean Indexing

In [50]:
a = [7, 3, 8, 3, 8, 6, 9, 1, 6, 4, 2, 3]
grid = np.array(a).reshape((3,4))
grid

array([[7, 3, 8, 3],
       [8, 6, 9, 1],
       [6, 4, 2, 3]])

In [52]:
# Alle Zahlen im grid, die kleiner 4 sind als 1D-array
grid[grid<4]

array([3, 3, 1, 2, 3])

In [53]:
# Alle Zeilen, die in der Spalte mit Index 2 eine gerade Zahl haben 
grid[grid[:,2]%2==0,:]     

array([[7, 3, 8, 3],
       [6, 4, 2, 3]])

In [54]:
# Alle Spalten, die in der Zeile mit Index 1 eine gerade Zahl haben.
grid[:,grid[1,:]%2==0]    

array([[7, 3],
       [8, 6],
       [6, 4]])