### Grids mit numpy

In [1]:
import numpy as np
import random

In [27]:
width, height = 8, 5
grid = np.zeros((height,width),dtype='int')
grid

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

Zufällige Positionen mit 1 füllen

In [28]:
anzahl = 5
kk = random.sample(range(width*height),anzahl)
print(kk)
for k in kk :
    x = k // width
    y = k % width
    grid[x,y] = 1
grid
 

[5, 27, 19, 33, 17]


array([[0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0]])

Anzahl der Einsen

In [29]:
np.count_nonzero(grid==1)   

5

Koordinaten der Einsen:

In [30]:
a = np.where(grid==1)
list(zip(a[0],a[1]))

[(0, 5), (2, 1), (2, 3), (3, 3), (4, 1)]

Indizes der Einsen:

In [31]:
a = np.where(grid==1)
b = list(zip(a[0],a[1]))
[p[0]*width+p[1] for p in b]

[5, 17, 19, 27, 33]

### Zufälliges Grid erzeugen

In [8]:
a = np.random.randint(10, size=(4, 4))
a

array([[7, 9, 9, 0],
       [8, 0, 7, 5],
       [2, 3, 5, 7],
       [8, 6, 8, 1]])

In [12]:
b = np.logical_and(2 < a, a < 8) 
a[b] = 0

In [13]:
a

array([[0, 9, 9, 0],
       [8, 0, 0, 0],
       [2, 0, 0, 0],
       [8, 0, 8, 1]])